### ISSUE TITLE
Using SSML with DictionaryLocaleStore

### ISSUE THREAD

**Issue by pbisku** [stoiveyp/Alexa.NET.LocaleSpeech#2]
Hi @stoiveyp 

I'm trying to use the DictionaryLocaleStore with SSML instead of plain text and I can't see how to use this.

Currently I'm using this:

```c#
internal static DictionaryLocaleSpeechStore SetupLanguageResources()
{
	var store = new DictionaryLocaleSpeechStore();

	store.AddLanguage("en", new Dictionary<string, object>
	{
		[LanguageKeys.Welcome] = "Welcome to the GEM!"
	});
 	
 	store.AddLanguage("de", new Dictionary<string, object>
	{
		[LanguageKeys.Welcome] = "<speak>Willkommen bei der <phoneme alphabet='x-sampa' ph='gEm'>GEM</phoneme>!</speak>"
	});
	
	return store;
}
```
And then using it like:

```c#
var welcomeMessage = await locale.Get(LanguageKeys.Welcome, null);
response = ResponseBuilder.Ask(welcomeMessage, null));
```

This doesn't work and Alexa speaks the XML-Code :-)

Can you give me a hint how to use SSML with the stores?

Many thanks - Peter

**Comment by stoiveyp** [comment]
Hi @pbisku 

The way it works is based on the object you add when you're setting up the language.

So adding a string will always return plain text.
For Ssml you can either return a `Speech` object (if you're building it in code)
or the library comes with a SpeechInformation object for full strings - so for your german dictionary you'd change it to

```csharp
store.AddLanguage("de", new Dictionary<string, object>
{
    [LanguageKeys.Welcome] = new SpeechInformation{
        Ssml = true,
        Speech="<speak>Willkommen bei der <phoneme alphabet='x-sampa' ph='gEm'>GEM</phoneme>!</speak>"
    }
});
```

Hope that helps!

**Comment by pbisku** [comment]
Many thanks for this info - works great!
